version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: scheds-backend
    container_name: scheds-backend
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app

volumes:
    node_modules:
